assets:
	./make_assets_release.sh || true

linux_x86:
	./build_app_linux_x86.sh

linux_arm:
	./build_app_linux_arm.sh

mac:
	./build_app_mac_arm.sh

mac_arm:
	./build_app_mac_arm.sh

mac_x86:
	./build_app_mac_x86.sh

windows:
	./build_app_windows_x86.sh

all:
	./build_app_all.sh
